src/Entity/Banner.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Integer;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BannerRepository")
 */
class Banner
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageMobile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageMobileMetaTitle;

    /**
     * @ORM\Column(type="string", length=510, nullable=true)
     */
    private $imageMobileMetaDescription;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageMetaTitle;

    /**
     * @ORM\Column(type="string", length=510, nullable=true)
     */
    private $imageMetaDescription;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $link = '#';

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isActive;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isLogged;

        /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isPromo;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $position = 0;

    /**
     * @ORM\ManyToOne(targetEntity="BannerType")
     * @ORM\JoinColumn(name="type_id", referencedColumnName="id")
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ga_event;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getImageMobile(): ?string
    {
        return $this->imageMobile;
    }

    public function setImageMobile(?string $imageMobile): self
    {
        $this->imageMobile = $imageMobile;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive(?bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }

    public function getIsPromo(): ?bool
    {
        return $this->isPromo;
    }

    public function setIsPromo(?bool $isPromo): self
    {
        $this->isPromo = $isPromo;

        return $this;
    }

    public function getType(): ?BannerType
    {
        return $this->type;
    }

    public function setType(?BannerType $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(?string $link): self
    {
        $this->link = $link;

        return $this;
    }

    public function getPosition(): ?int
    {
        return $this->position;
    }

    public function setPosition(?int $position): self
    {
        $this->position = $position;

        return $this;
    }

    public function getIsLogged(): ?int
    {
        return $this->isLogged;
    }

    public function setIsLogged(?int $isLogged): self
    {
        $this->isLogged = $isLogged;

        return $this;
    }

    public function getImageMobileMetaTitle(): ?string
    {
        return $this->imageMobileMetaTitle;
    }

    public function setImageMobileMetaTitle(?string $imageMobileMetaTitle): self
    {
        $this->imageMobileMetaTitle = $imageMobileMetaTitle;

        return $this;
    }

    public function getImageMobileMetaDescription(): ?string
    {
        return $this->imageMobileMetaDescription;
    }

    public function setImageMobileMetaDescription(?string $imageMobileMetaDescription): self
    {
        $this->imageMobileMetaDescription = $imageMobileMetaDescription;

        return $this;
    }

    public function getImageMetaTitle(): ?string
    {
        return $this->imageMetaTitle;
    }

    public function setImageMetaTitle(?string $imageMetaTitle): self
    {
        $this->imageMetaTitle = $imageMetaTitle;

        return $this;
    }

    public function getImageMetaDescription(): ?string
    {
        return $this->imageMetaDescription;
    }

    public function setImageMetaDescription(?string $imageMetaDescription): self
    {
        $this->imageMetaDescription = $imageMetaDescription;

        return $this;
    }

    public function getGaEvent(): ?string
    {
        return $this->ga_event;
    }

    public function setGaEvent(?string $ga_event): self
    {
        $this->ga_event = $ga_event;

        return $this;
    }

}

src/Entity/Leads.php
<?php

namespace App\Entity;

use App\Repository\LeadsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LeadsRepository::class)
 */
class Leads
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_facebook;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_google;

    /**
     * @ORM\ManyToOne(targetEntity=Role::class, inversedBy="leads")
     */
    private $role;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_newsletter;

    /**
     * @ORM\OneToMany(targetEntity=LeadEmblue::class, mappedBy="lead")
     */
    private $leadEmblues;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $gender;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $birthday;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $cnpj;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $cpf;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $estate_address;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $educationalLevel;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $friendIndication;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $crf;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $state;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $step;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cellphone;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;


    public function __construct()
    {
        $this->leadEmblues = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRole(): ?Role
    {
        return $this->role;
    }

    public function setRole(?Role $role): self
    {
        $this->role = $role;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getIsFacebook(): ?bool
    {
        return $this->is_facebook;
    }

    public function setIsFacebook(bool $is_facebook): self
    {
        $this->is_facebook = $is_facebook;

        return $this;
    }

    public function getIsGoogle(): ?bool
    {
        return $this->is_google;
    }

    public function setIsGoogle(bool $is_google): self
    {
        $this->is_google = $is_google;

        return $this;
    }

    public function getIsNewsletter(): ?bool
    {
        return $this->is_newsletter;
    }

    public function setIsNewsletter(?bool $is_newsletter): self
    {
        $this->is_newsletter = $is_newsletter;

        return $this;
    }

    /**
     * @return Collection|LeadEmblue[]
     */
    public function getLeadEmblues(): Collection
    {
        return $this->leadEmblues;
    }

    public function addLeadEmblue(LeadEmblue $leadEmblue): self
    {
        if (!$this->leadEmblues->contains($leadEmblue)) {
            $this->leadEmblues[] = $leadEmblue;
            $leadEmblue->setLead($this);
        }

        return $this;
    }

    public function removeLeadEmblue(LeadEmblue $leadEmblue): self
    {
        if ($this->leadEmblues->removeElement($leadEmblue)) {
            // set the owning side to null (unless already changed)
            if ($leadEmblue->getLead() === $this) {
                $leadEmblue->setLead(null);
            }
        }

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(?string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getBirthday(): ?string
    {
        return $this->birthday;
    }

    public function setBirthday(?string $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getCnpj(): ?string
    {
        return $this->cnpj;
    }

    public function setCnpj(?string $cnpj): self
    {
        $this->cnpj = $cnpj;

        return $this;
    }

    public function getCpf(): ?string
    {
        return $this->cpf;
    }

    public function setCpf(?string $cpf): self
    {
        $this->cpf = $cpf;

        return $this;
    }

    public function getState(): ?string
    {
        return $this->state;
    }

    public function setState(?string $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getEducationalLevel(): ?string
    {
        return $this->educationalLevel;
    }

    public function setEducationalLevel(?string $educationalLevel): self
    {
        $this->educationalLevel = $educationalLevel;

        return $this;
    }

    public function getFriendIndication(): ?string
    {
        return $this->friendIndication;
    }

    public function setFriendIndication(?string $friendIndication): self
    {
        $this->friendIndication = $friendIndication;

        return $this;
    }

    public function getCrf(): ?string
    {
        return $this->crf;
    }

    public function setCrf(?string $crf): self
    {
        $this->crf = $crf;

        return $this;
    }

    public function getStep(): ?string
    {
        return $this->step;
    }

    public function setStep(?string $step): self
    {
        $this->step = $step;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getCellphone(): ?string
    {
        return $this->cellphone;
    }

    public function setCellphone(?string $cellphone): self
    {
        $this->cellphone = $cellphone;

        return $this;
    }

    public function getEstateAddress(): ?string
    {
        return $this->estate_address;
    }

    public function setEstateAddress(?string $estate_address): self
    {
        $this->estate_address = $estate_address;

        return $this;
    }
}

templates/admin_banner/edit.html.twig
{% extends 'admin.html.twig' %}

{% block title %}CURSO | BANNER
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
            <div class="box">

                <div class="box-header with-border">
                    <h3 class="box-title">Editar Banner</h3>
                </div>

                <form enctype="multipart/form-data" method="POST">

                    <div class="box-body">
                        <div class="form-group">
                            <label for="banner_name">title</label>
                            {# <input id="banner_name" name="banner[title]" type="text" value="{{banner.title}}" /> #}
                            <textarea class="ckeditor" id="banner_name" name="banner[title]" type="text">{{ banner.title }}</textarea>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Descrição</label>
                            {# <input class="form-control" type="text" value="{{banner.description}}"  name="banner[description]" /> #}
                            <textarea class="ckeditor" id="banner_description" name="banner[description]" type="text">{{ banner.description }}</textarea>
                        </div>
                         <div class="form-group">
                            <label class="control-label">Link</label>
                            <input class="form-control" type="text"  name="banner[link]" value="{{banner.link}}"/>
                        </div>
                        <div class="form-group-double">
                            <div class="form-group">
                                <label for="banner_type">Local de Exibição</label>
                                <select id="banner_type" name="banner[type]">
                                    {% for t in types %}
                                        <option value="{{t.id}}" {{ banner.type.id == t.id ? 'selected' : '' }}>{{t.name}}</li>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="banner_isActive">Ativo</label>
                                <input {{ banner.isActive ? 'checked' : '' }} data-toggle="toggle" id="banner_isActive" name="banner[isActive]" type="checkbox">
                            </div>
                        </div>
                        <div class="form-group-double">
                            <div class="form-group">
                                <div id="preview-web" class="preview-img">
                                    <img   src="{{ asset(banner.image) }}">
                                </div>
                                <label for="banner_image">Imagem</label>
                                <input accept=".jpg,.png,.webp,.jpeg" id="banner_image" name="banner[image]" type="file"/>
                               <label id="mensagem-web" style="display:none;">Imagem maior que o permitido.  Selecione imagem de até 1MB.</label>
                            </div>
                            <div class="form-group">
                                <div id="preview-mobile" class="preview-img">
                                    <img  src="{{ asset(banner.imageMobile) }}">
                                </div>
                                <label for="banner_imageMobile">Imagem Mobile</label>
                                <input accept=".jpg,.png,.webp,.jpeg" id="banner_imageMobile" name="banner[imageMobile]" type="file"/>
                                <label id="mensagem-mobile" style="display:none;">Imagem maior que o permitido.  Selecione imagem de até 1MB.</label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="banner_name">GA eventLabel</label>
                            <input class="form-control" type="text" name="banner[ga_event]" value="{{ banner.gaEvent }}"/>
                        </div>
                        <div class="form-group">
                            <label for="position_name">Ordem</label>

                            <select id="position_name" name="banner[position]" />
                            {% for i in 0..10 %}
                                <option value="{{ i }}" {{ banner.position == i ? 'selected' : ''}}>{{ i }}</option>
                            {% endfor %}
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="banner_isLogged">Deseja exibir o banner somente quando estiver logado?</label>
                            <input {{ banner.isLogged ? 'checked' : '' }} data-toggle="toggle" id="banner_isLogged" name="banner[isLogged]" type="checkbox">
                        </div>

                         <div class="form-group">
                            <label for="banner_isPromo">Promoção</label>
                            <input {{ banner.isPromo ? 'checked' : '' }} data-toggle="toggle" id="banner_isPromo" name="banner[isPromo]" type="checkbox">
                        </div>

                    </div>

                    <div class="box-footer">
                        <button  type="" class="btn btn-success">Salvar</button>
                        <a class="btn btn-default" href="{{ path('admin_banner_list') }}">Cancelar</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}

    <script>
    
        $("form").on("submit", function(){
            showLoading();
        });

        $('#banner_image').on('change', function (){
        
          readSize("banner_image", "mensagem-web","preview-web",0);
        });

        $('#banner_imageMobile').on('change', function(){
            
          readSize("banner_imageMobile", "mensagem-mobile","preview-mobile",0);
         
        });
        
        function readSize(id, idMessage,idPreview,index){
              if(parseInt(document.getElementById(id).files[index].size) > 1048576){
                $(`#${id}`).val("");
                document.getElementById(idPreview).style.display = "none";
                document.getElementById(idMessage).style.cssText = " display: block;color: red;font-size: larger";
                
                return ;
               }else {
            
              document.getElementById(idPreview).style.display = "block";
              document.getElementById(idMessage).style.cssText = " display: none";
              readURL(document.getElementById(id));
            
               }
        }

        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    console.log();
                    $(input).siblings('.preview-img').html('<img src="' + e.target.result + '">');
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
        
    </script>

{% endblock %}

templates/admin_banner/list.html.twig
{% extends 'admin.html.twig' %}

{% block title %}BANNER | LISTAR
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
            <div class="box">

                <div class="box-header with-border">
                    <h3 class="box-title">Banners</h3>
                </div>

                <div class="box-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-hover table-bordered">
                            <thead>
                                <tr>
                                    <th>Id</th>

                                    <th>Nome</th>
                                    
                                    <th>Tipo</th>

                                    <th>Descricao</th>

                                    <th>Ativo</th>

                                    <th>Criado Em</th>

                                    <th>Ações</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% if banners|length > 0 %}
                                    {% for banner in banners %}
                                        <tr>
                                            <td class="center">
                                                <a href="{{ path('admin_banner_edit', { 'id': banner.id }) }}">
                                                    {{ banner.id }}
                                                </a>
                                            </td>
                                            <td>{{ banner.title }}</td>
                                            
                                            <td>{{ banner.type ? banner.type.name : '---' }}</td>
                                            <td>{{ banner.description }}</td>
                                            <td class="center">
                                                {% if banner.isActive %}
                                                    <span class="label label-success">Sim</span>
                                                {% else %}
                                                    <span class="label label-danger">Não</span>
                                                {% endif %}
                                            </td>
                                            <td class="center">
                                                {% if banner.createdAt %}
                                                    {{ banner.createdAt|date('d/m/Y H:i:s') }}
                                                {% endif %}
                                            </td>
                                            <td class="center">
                                                <a class="btn btn-primary btn-sm" href="{{ path('admin_banner_edit', { 'id': banner.id}) }}">
                                                    Editar
                                                    <i class="fa fa-edit"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                {% else %}
                                    <tr>
                                        <td colspan="8">Nenhum registro foi encontrado.</td>
                                    </tr>
                                {% endif %}
                            </tbody>
                        </table>
                    </div>

                </div>

                <div class="box-paginator">
                    {{ knp_pagination_render(banners) }}
                </div>

                <div class="box-footer">
                    <a class="btn btn-success btn-sm" href="{{ path('admin_banner_new') }}">
                        Novo
                        <i class="fa fa-plus"></i>
                    </a>
                </div>

            </div>
        </div>
    </div>
{% endblock %}