src/Entity/Leads.php
<?php

namespace App\Entity;

use App\Repository\LeadsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LeadsRepository::class)
 */
class Leads
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_facebook;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_google;

    /**
     * @ORM\ManyToOne(targetEntity=Role::class, inversedBy="leads")
     */
    private $role;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_newsletter;

    /**
     * @ORM\OneToMany(targetEntity=LeadEmblue::class, mappedBy="lead")
     */
    private $leadEmblues;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $gender;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $birthday;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $cnpj;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $cpf;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $estate_address;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $educationalLevel;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $friendIndication;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $crf;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $state;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $step;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cellphone;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;


    public function __construct()
    {
        $this->leadEmblues = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRole(): ?Role
    {
        return $this->role;
    }

    public function setRole(?Role $role): self
    {
        $this->role = $role;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getIsFacebook(): ?bool
    {
        return $this->is_facebook;
    }

    public function setIsFacebook(bool $is_facebook): self
    {
        $this->is_facebook = $is_facebook;

        return $this;
    }

    public function getIsGoogle(): ?bool
    {
        return $this->is_google;
    }

    public function setIsGoogle(bool $is_google): self
    {
        $this->is_google = $is_google;

        return $this;
    }

    public function getIsNewsletter(): ?bool
    {
        return $this->is_newsletter;
    }

    public function setIsNewsletter(?bool $is_newsletter): self
    {
        $this->is_newsletter = $is_newsletter;

        return $this;
    }

    /**
     * @return Collection|LeadEmblue[]
     */
    public function getLeadEmblues(): Collection
    {
        return $this->leadEmblues;
    }

    public function addLeadEmblue(LeadEmblue $leadEmblue): self
    {
        if (!$this->leadEmblues->contains($leadEmblue)) {
            $this->leadEmblues[] = $leadEmblue;
            $leadEmblue->setLead($this);
        }

        return $this;
    }

    public function removeLeadEmblue(LeadEmblue $leadEmblue): self
    {
        if ($this->leadEmblues->removeElement($leadEmblue)) {
            // set the owning side to null (unless already changed)
            if ($leadEmblue->getLead() === $this) {
                $leadEmblue->setLead(null);
            }
        }

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(?string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getBirthday(): ?string
    {
        return $this->birthday;
    }

    public function setBirthday(?string $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getCnpj(): ?string
    {
        return $this->cnpj;
    }

    public function setCnpj(?string $cnpj): self
    {
        $this->cnpj = $cnpj;

        return $this;
    }

    public function getCpf(): ?string
    {
        return $this->cpf;
    }

    public function setCpf(?string $cpf): self
    {
        $this->cpf = $cpf;

        return $this;
    }

    public function getState(): ?string
    {
        return $this->state;
    }

    public function setState(?string $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getEducationalLevel(): ?string
    {
        return $this->educationalLevel;
    }

    public function setEducationalLevel(?string $educationalLevel): self
    {
        $this->educationalLevel = $educationalLevel;

        return $this;
    }

    public function getFriendIndication(): ?string
    {
        return $this->friendIndication;
    }

    public function setFriendIndication(?string $friendIndication): self
    {
        $this->friendIndication = $friendIndication;

        return $this;
    }

    public function getCrf(): ?string
    {
        return $this->crf;
    }

    public function setCrf(?string $crf): self
    {
        $this->crf = $crf;

        return $this;
    }

    public function getStep(): ?string
    {
        return $this->step;
    }

    public function setStep(?string $step): self
    {
        $this->step = $step;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getCellphone(): ?string
    {
        return $this->cellphone;
    }

    public function setCellphone(?string $cellphone): self
    {
        $this->cellphone = $cellphone;

        return $this;
    }

    public function getEstateAddress(): ?string
    {
        return $this->estate_address;
    }

    public function setEstateAddress(?string $estate_address): self
    {
        $this->estate_address = $estate_address;

        return $this;
    }
}

src/Entity/QuizAll.php
<?php

namespace App\Entity;

use App\Repository\QuizAllRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=QuizAllRepository::class)
 */
class QuizAll
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $slug;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_active;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_public;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_pharmaceutical;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_clerk;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_store_manager;

    /**
     * @ORM\OneToMany(targetEntity=QuizAllQuestions::class, mappedBy="quiz_all")
     */
    private $quizAllQuestions;

    /**
     * @ORM\OneToMany(targetEntity=QuizAllRuleResult::class, mappedBy="quiz_all")
     */
    private $quizAllRuleResults;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image_alt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\ManyToMany(targetEntity=SpecialCampaign::class, mappedBy="quiz_all")
     */
    private $specialCampaigns;

    public function __construct()
    {
        $this->quizAllQuestions = new ArrayCollection();
        $this->quizAllRuleResults = new ArrayCollection();
        $this->specialCampaigns = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(?bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function getIsPublic(): ?bool
    {
        return $this->is_public;
    }

    public function setIsPublic(?bool $is_public): self
    {
        $this->is_public = $is_public;

        return $this;
    }

    public function getIsPharmaceutical(): ?bool
    {
        return $this->is_pharmaceutical;
    }

    public function setIsPharmaceutical(?bool $is_pharmaceutical): self
    {
        $this->is_pharmaceutical = $is_pharmaceutical;

        return $this;
    }

    public function getIsClerk(): ?bool
    {
        return $this->is_clerk;
    }

    public function setIsClerk(?bool $is_clerk): self
    {
        $this->is_clerk = $is_clerk;

        return $this;
    }

    public function getIsStoreManager(): ?bool
    {
        return $this->is_store_manager;
    }

    public function setIsStoreManager(?bool $is_store_manager): self
    {
        $this->is_store_manager = $is_store_manager;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection|QuizAllQuestions[]
     */
    public function getQuizAllQuestions(): Collection
    {
        return $this->quizAllQuestions;
    }

    public function addQuizAllQuestion(QuizAllQuestions $quizAllQuestion): self
    {
        if (!$this->quizAllQuestions->contains($quizAllQuestion)) {
            $this->quizAllQuestions[] = $quizAllQuestion;
            $quizAllQuestion->setQuizAll($this);
        }

        return $this;
    }

    public function removeQuizAllQuestion(QuizAllQuestions $quizAllQuestion): self
    {
        if ($this->quizAllQuestions->removeElement($quizAllQuestion)) {
            // set the owning side to null (unless already changed)
            if ($quizAllQuestion->getQuizAll() === $this) {
                $quizAllQuestion->setQuizAll(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|QuizAllRuleResult[]
     */
    public function getQuizAllRuleResults(): Collection
    {
        return $this->quizAllRuleResults;
    }

    public function addQuizAllRuleResult(QuizAllRuleResult $quizAllRuleResult): self
    {
        if (!$this->quizAllRuleResults->contains($quizAllRuleResult)) {
            $this->quizAllRuleResults[] = $quizAllRuleResult;
            $quizAllRuleResult->setQuizAll($this);
        }

        return $this;
    }

    public function removeQuizAllRuleResult(QuizAllRuleResult $quizAllRuleResult): self
    {
        if ($this->quizAllRuleResults->removeElement($quizAllRuleResult)) {
            // set the owning side to null (unless already changed)
            if ($quizAllRuleResult->getQuizAll() === $this) {
                $quizAllRuleResult->setQuizAll(null);
            }
        }

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getImageAlt(): ?string
    {
        return $this->image_alt;
    }

    public function setImageAlt(?string $image_alt): self
    {
        $this->image_alt = $image_alt;

        return $this;
    }

    /**
     * @return Collection|SpecialCampaign[]
     */
    public function getSpecialCampaigns(): Collection
    {
        return $this->specialCampaigns;
    }

    public function addSpecialCampaign(SpecialCampaign $specialCampaign): self
    {
        if (!$this->specialCampaigns->contains($specialCampaign)) {
            $this->specialCampaigns[] = $specialCampaign;
            $specialCampaign->addQuizAll($this);
        }

        return $this;
    }

    public function removeSpecialCampaign(SpecialCampaign $specialCampaign): self
    {
        if ($this->specialCampaigns->removeElement($specialCampaign)) {
            $specialCampaign->removeQuizAll($this);
        }

        return $this;
    }
}

templates/promo_thirty_day_movement/cron-upadate-vendedores.html.twig
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Cron ranking vendedores - Portal Neo Pharma</title>
    <link rel="stylesheet" type="text/css" media="all" href="{{ asset('_dist/css/main.min.css') }}">
</head>
<body>
    <div class="container-fluid">
        <div class="container">
            <div class="space-h-40" id="content">
                <h1 class="text-red text-center space-h-20">Atualizando ranking vendedores</h1>
            </div>
        </div>
    </div>
    <script src="{{ asset('_dist/js/jquery.min.js') }}"></script>

    <script>
        enviaCron(); 

        function enviaCron() {
            $.ajax({
                url: '{{ path('promo_thirty_day_movement_point_update_vendas') }}',
                type: 'GET',
                data: {'q':true}
            }).done(function (response) {
                if(response.message == 'OK') {
                    $('#content').append('<p>'+ response.quantity_sent +' vendedores atualizados.</p>');
                    $('#content').append('<p>&nbsp;</p>');
                    enviaCron();
                }
                if(response.message == 'Todos os vendedores tiveram as suas pontuação atualizadas com sucesso.') {
                    $('#content').append('<p>'+ response.message +'</p>')
                }
            }).fail(function (response) {
                $('#content').append('<p>erro: '+ response +'</p>')
            });
        }
    </script>
</body>
</html>

templates/promo_thirty_day_movement/index.html.twig
{% extends 'base.html.twig' %}
{% set metadescription = '' %}
{% set metatitle = '' %}
{% block title %}Ranking - Desafio 30 dias de Movimento{% endblock %}
    
{% block body %}

    <div class="page-30-dias-ranking">
        <div class="text-center header-top">
            <div class="container">
                <h2>Ranking</h2>
                <p class="space-h-10">
                    Saiba quantos pontos você tem. 
                </p>
            </div>
        </div>

        <div class="src-points">
            <div class="container">
                {# <form> #}
                <div class="form">
                    <h3>
                        Preencha com seu código de indicação e veja quantos pontos já conquistou. 
                    </h3>
                    <span class="error" id="search-points-error"></span>
                    <div class="d-flex">
                        <input type="text" id="code-point" alt="" title="" />
                        <button type="button" id="btn-points"><i class="fa fa-search"></i></button>
                    </div>

                    <div class="text-center result-box">
                        <h4 id="msg-points"></h4>
                        <p>
                            <big id="result-points"></big>
                        </p>
                    </div>
                </div>
                {# </form> #}
            </div>
        </div>
    </div>

{% endblock %}

{% block javascripts %} 
    <script src="{{ asset('vendor/jquery.mask.js') }}"></script>
    <script>
        var url  = "{{ path('promo_thirty_day_movement') }}";

        $('#btn-points').on('click', function(e){
            var $this = $(this),
                msg = $('#msg-points'),
                result = $('#result-points');

            $.ajax({
                url: url,
                type: "POST",
                dataType: "json",
                cache: false,
	            headers: { "cache-control": "no-cache" },
                data: {
                    'q': 'search',
                    'cp': $('#code-point').val(),
                },
                beforeSend: function(e){
                  msg.text('Carregando...');
                  result.text('');
                  $this.attr("disabled", true);
                  $('#search-points-error').text('');
                },
                success: function (response) {
                    if(response.status){
                       msg.text('Resultado:');
                       result.text(response.points);
                    }else{
                        if(response.hasOwnProperty('message')){
                           $('#search-points-error').text(response.message);
                        }
                        msg.text('');
                    }                   
                    $this.attr("disabled", false);
                } 
            });
        });

        $('#code-point').on("keyup", function(){
            $('#search-points-error').text('');
        });
    </script>

{% endblock %}

templates/promo_thirty_day_movement/ranking.html.twig
{% extends 'base.html.twig' %}
{% set metadescription = '' %}
{% set metatitle = '' %}
{% block title %}Desafio 30 dias de Movimento - Ranking{% endblock %}

{% block body %}
    <div class="page-desafio-30-dias page-desafio-30-dias-ranking">
        <div class="container">
            <h1 class="text-center space-h-30">Ranking</h1>
        </div>
        <div class="container text-center space-h-30">
            <div class="btns-top">
                <a href="{{ path('promo_thirty_day_movement_videos') }}">Vídeos</a>
                <a href="{{ path('promo_thirty_day_movement_ranking_bf') }}">Ranking</a>
                <a href="{{ path('promo_thirty_day_movement_winners_week') }}">Prêmios Semanais</a>
                <a href="{{ path('promo_thirty_day_movement_landpage') }}">Campanha</a>
            </div>
        </div>
        <div class="tarja">
            <img src="{{ asset('_dist/image/img/medal.png') }}" alt="">
        </div>
        <div class="container">
            <div class="ranking-list">
                {% if ranking|length > 0 %}
                    {% for rank in ranking %}
                        {% if loop.index  <= 50 %}
                            <div class="ranking-item">
                                <div class="ranking-name">
                                   {{ rank.user.name }}
                                </div>
                                <div class="ranking-points" data-cadastro="{{ rank.createdAt|date('d/m/Y H:i:s') }}">
                                    {{ rank.points }}
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                {% else %}
                    <h2>Nenhum resultado a ser exibido.</h2>
                {% endif %}
            </div>
        </div>

        <div class="space-h-30 text-center">
            <a href="#" class="btn-more">Confira mais</a>
        </div>
        {% if ranking|length > 0 %}
        <div class="space-h-30 text-center">
            <span>
                <strong>Última atualização em:</strong> {{ ranking[0].updatedAt|date('d/m/Y H:i:s') }}
            </span>
        </div>  
        {% endif %}
    </div>  
{% endblock %}

{% block javascripts %}
    <script>
        $("document").ready(function(){
            $( ".ranking-item" ).each(function(index) {
                $(this).addClass('ranking-item-'+ parseInt(index + 1));
                
                if(index > 9){
                    $(this).hide();
                    
                    $('.btn-more').on('click', function(e){
                        e.preventDefault();
                        $( ".ranking-item" ).show();
                        $(this).hide();
                        return false;
                    });
                }
            });
        });
    </script>

{% endblock %}

templates/promo_thirty_day_movement/register.html.twig
{% extends 'base.html.twig' %}
{% set metadescription = '' %}
{% set metatitle = '' %}
{% block title %}Cadastro Desafio 30 dias de Movimento{% endblock %}

{% block body %}
    <div class="text-center">
        <img src="{{ asset('_dist/image/img/banner-desafio.jpg') }}" alt="30 Dias de Movimento" class="hidden-xs">
        <img src="{{ asset('_dist/image/img/banner-desafio-mobile.jpg') }}" alt="30 Dias de Movimento" class="visible-xs">

        
    </div>
    <div class="container">
        <div class="login-forms-box">
            <div class="text-center space-h-10">
                <h2 id="lightbox-message">Desafio <span class="exclude-text">30</span> 52 Dias de Movimento </h2>
                <p class="space-h-10">
                    <big>
                        Cadastre-se aqui e concorra até <strong>R$ 1.000</strong> em prêmios. Ainda dá tempo!! 
                    </big>
                </p>
                <p class="space-h-10" id="alert-promo" style="color: red; font-weight: bold;"></p>
            </div>
            <form method="post" class="form" id="form" enctype="multipart/form-data">
                <div class="space-h-10">
                    <label for="register-instagram">Instagram * <span class="error" id="instagram-error"></span></label>
                    <div class="d-flex">
                        <i class="fa fa-instagram icon-form"></i>
                        <input type="text" id="register-instagram" name="formPromo[instagram]" class="form-control cdt_mid_frm_nome" required maxlength="30">
                    </div>
                </div>
                <div class="space-h-10">
                    <label for="register-whatsapp">WhatsApp * <span class="error" id="whatsapp-error"></span></label>
                    <div class="d-flex">
                        <i class="fa fa-whatsapp icon-form"></i>
                        <input type="text" id="register-whatsapp" name="formPromo[whatsapp]" class="form-control cdt_mid_frm_email" required>
                    </div>
                </div>
                <div>
                    <div class="form-check">
                        <input type="checkbox" name="term" id="agree-term" class="cdt_mid_frm_declaro term-checked" required/>
                        <label for="agree-term" class="form-check-label">
                            <small class="text-gray">Declaro que li e aceito este​ <a href="{{ path('promo_thirty_day_movement_regulation') }}" target="_blank" class="show-terms">regulamento</a>. <span class="error termo-use-error" id="term-g-error"></span></small>
                        </label>
                    </div>
                </div>
                <div class="space-h-20">
                    <button type="button" id="btn-login-gestor" class="btn-default btn-special-pink btn-register-gestor btn-full btn-large cdt_mid_frm_sbm_cadastar">Participar da campanha</button>
                </div>
            </form>
        </div>

        <!-- Modal de Confirmação -->
        <div class="modal-default modal-image" id="modal-promo30day">
            <div class="confirm-modal-image">
                <div class="confirm-modal-image-content">
                    {# <a class="close-modal" id="close-modal-image" onclick="closeModal()">X</a> #}
                    <figure class="container">
                        <a href="{{ path('promo_thirty_day_movement_landpage') }}">
                          {% if app.user.isPharmaceutical %}
                            <img src="{{ asset('_dist/image/img/popup2-desktop.jpg') }}" alt="30 Dias de Movimento" class="hidden-xs">
                            <img src="{{ asset('_dist/image/img/popup2.jpg') }}" alt="30 Dias de Movimento" class="visible-xs">
                          {% else %}
                            <img src="{{ asset('_dist/image/img/popup1-desktop.jpg') }}" alt="30 Dias de Movimento" class="hidden-xs">
                            <img src="{{ asset('_dist/image/img/popup1.jpg') }}" alt="30 Dias de Movimento" class="visible-xs">
                          {% endif %}
                        </a>
                    </figure>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %} 
    <script src="{{ asset('vendor/jquery.mask.js') }}"></script>
    <script>
        var url  = "{{ path('promo_thirty_day_movement_create') }}";

        $('#btn-login-gestor').on('click', function(e){
            var $this = $(this),
                term = 0;

            if ($('.term-checked').is(':checked')){
                term = 1;
            } 

            $.ajax({
                url: url,
                type: "POST",
                dataType: "json",
                cache: false,
	            headers: { "cache-control": "no-cache" },
                data: {
                    'u': {{ app.user.id }},
                    'instagram': $('[name="formPromo[instagram]"]').val(), 
                    'whatsapp': $('[name="formPromo[whatsapp]"]').val(), 
                    'regulament': term,
                },
                beforeSend: function(e){
                  $this.text('Carregando...');
                  $this.attr("disabled", true);
                  $('#alert-promo').text('');
                },
                success: function (response) {
                    if(response.status){
                        modalPromoThirtyDays();
                    }else{
                        if(response.errors.hasOwnProperty('instagram')){
                           $('#instagram-error').text(response.errors.instagram);
                        }

                        if(response.errors.hasOwnProperty('whatsapp')){
                            $('#whatsapp-error').text(response.errors.whatsapp);
                        }

                        if (response.errors.hasOwnProperty('regulament') ) {
                            $('#term-g-error').text(response.errors.regulament);
                        }

                        if (response.errors.hasOwnProperty('alert') ) {
                            $('#alert-promo').text(response.errors.alert);
                        }
                    }

                    $this.text('Participar da campanha');
                    $this.attr("disabled", false);
                } 
            });
        });

        $('[name="formPromo[instagram]"]').on("keyup", function(){
            $('#instagram-error').text('');
        });

        $('[name="formPromo[whatsapp]"]').on("keyup", function(){
            $('#whatsapp-error').text('');
        });

        $('.term-checked').on("click", function(){
            if ($(this).is(':checked')) {
                $('#term-g-error').text('');
            }
        });

        function modalPromoThirtyDays() {
            //$('#modal-promo30day').removeClass('hide');
            //$('#modal-promo30day').addClass('show');
             
            if($('#modal-promo30day').hasClass('open-menu')){
                $('#modal-promo30day').removeClass('open-modal');
            } else{
                $('#modal-promo30day').addClass('open-modal');
            }
        }

        $('[name="formPromo[whatsapp]"]').mask('(00) 00000-0000');
    </script>

{% endblock %}